version: '3.8'
services:
  app:
    build: .
    depends_on:
      - pgdb
    ports:
      - "5000:5000"
    environment:
      - PG_DB_CONFIG=pgdb-hexClad-hexClad-5432-Count_A_Dram
    networks:
      - app-network
  pgdb:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=Count_A_Dram
      - POSTGRES_USER=hexClad
      - POSTGRES_PASSWORD=hexClad
    ports:
      - '5432:5432'
    volumes: 
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db:
    driver: local