version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=Count_A_Dram
      - POSTGRES_USER=hexClad
      - POSTGRES_PASSWORD=hexClad
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local